name: Create IOS Builds

on:
  pull_request:
    types: [ labeled ]
jobs:

build_ios:
  type: build # This job type creates a production build for iOS
  if: github.event.label.name == 'build-ios'
  ref: ${{ github.event.pull_request.head.ref }}
  env:
    APP_ENV: production
  params:
    platform: ios
    profile: production
